# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "AFKissXMLRequestOperationLib" do
  pod "AFNetworking", "~> 2.1"
  pod "KissXML", "~> 5.0"
end

target "AFKissXMLRequestOperationLibTests" do

end

